import type { Metadata } from "next";
import Providers from "@/app/providers";
import Nav from "@/components/nav";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <Nav />
        {children}
      </Providers>
      </body>
    </html>
  );
}
